// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NC.Entities.Models;

public  class NoobzCordContext : DbContext
{
    public NoobzCordContext(DbContextOptions<NoobzCordContext> options)
      : base(options)
    {
    }

    public DbSet<Token> Tokens { get; set; }

    public DbSet<Translation> Translations { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<UserPassword> UserPasswords { get; set; }

    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //{
    //    base.OnConfiguring(optionsBuilder);
    //    optionsBuilder.UseSnakeCaseNamingConvention();
    //    optionsBuilder.UseNpgsql("Host=localhost;Database=NoobzCord;Username=postgres;Password=123456789");
    //}
}