// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Entities.Models;

[Table("Token")]
public partial class Token
{
    [Key]
    public Guid ID { get; set; }

    public Guid UserID { get; set; }

    public string? Data { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Expires { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UsedOn { get; set; }

    public byte Status { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Tokens")]
    public virtual User User { get; set; } = null!;
}