// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Entities.Models;

[Table("Translation")]
[Index("Name", "Language", Name = "IX_Translation", IsUnique = true)]
public partial class Translation
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    [StringLength(10)]
    public string Language { get; set; } = null!;

    public string Value { get; set; } = null!;
}