// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Entities.Models;

[Table("User")]
[Index("Contact", Name = "IX_User_Contact", IsUnique = true)]
[Index("Name", Name = "IX_User_Name", IsUnique = true)]
public partial class User
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(20)]
    public string Name { get; set; } = null!;

    [StringLength(50)]
    public string Contact { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime RegistrationDate { get; set; }

    public byte Status { get; set; }

    public byte Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();

    [InverseProperty("User")]
    public virtual UserPassword? UserPassword { get; set; }
}