// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Data.Models;

[Keyless]
[Table("Channel")]
public partial class Channel
{
    public Guid ID { get; set; }

    [StringLength(20)]
    public string Name { get; set; } = null!;

    public byte Kind { get; set; }
}