// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Data.Models;

[Table("Parameter")]
[Index("Name", Name = "IX_Parameter_Name", IsUnique = true)]
public partial class Parameter
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    public string Value { get; set; } = null!;
}