// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Data.Models;

[Table("UserPassword")]
public partial class UserPassword
{
    [Key]
    public Guid UserID { get; set; }

    [StringLength(256)]
    public string Hash { get; set; } = null!;

    [ForeignKey("UserID")]
    [InverseProperty("UserPassword")]
    public virtual User User { get; set; } = null!;
}