// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NC.Data.Models;

[Table("UserToken")]
public partial class UserToken
{
    [Key]
    public Guid ID { get; set; }

    public Guid UserID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Expires { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UsedAt { get; set; }

    public byte Status { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserTokens")]
    public virtual User User { get; set; } = null!;
}