// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NC.Entities.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NC.Entities.Migrations
{
    [DbContext(typeof(NoobzCordContext))]
    partial class NoobzCordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NC.Entities.Models.Token", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UsedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_on");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ID")
                        .HasName("pk_token");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_token_user_id");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("NC.Entities.Models.Translation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("ID")
                        .HasName("pk_translation");

                    b.HasIndex(new[] { "Name", "Language" }, "IX_Translation")
                        .IsUnique()
                        .HasDatabaseName("ix_translation_name_language");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("NC.Entities.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("ID")
                        .HasName("pk_user");

                    b.HasIndex(new[] { "Contact" }, "IX_User_Contact")
                        .IsUnique()
                        .HasDatabaseName("ix_user_contact");

                    b.HasIndex(new[] { "Name" }, "IX_User_Name")
                        .IsUnique()
                        .HasDatabaseName("ix_user_name");

                    b.ToTable("User");
                });

            modelBuilder.Entity("NC.Entities.Models.UserPassword", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash");

                    b.HasKey("UserID")
                        .HasName("pk_user_password");

                    b.ToTable("UserPassword");
                });

            modelBuilder.Entity("NC.Entities.Models.Token", b =>
                {
                    b.HasOne("NC.Entities.Models.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NC.Entities.Models.UserPassword", b =>
                {
                    b.HasOne("NC.Entities.Models.User", "User")
                        .WithOne("UserPassword")
                        .HasForeignKey("NC.Entities.Models.UserPassword", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_password_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NC.Entities.Models.User", b =>
                {
                    b.Navigation("Tokens");

                    b.Navigation("UserPassword");
                });
#pragma warning restore 612, 618
        }
    }
}
